-- ============================================================================
-- 03_rbac.sql — Context tree + RBAC (Spatie-equivalent + custom context layer)
-- ----------------------------------------------------------------------------
-- In the real app, permissions/roles/role_has_permissions/model_has_roles are
-- generated by spatie/laravel-permission (teams enabled, team key = tenant_id).
-- Here we materialize equivalent tables with UUID keys so the whole schema is
-- consistent and the custom context layer can FK into them.
-- ============================================================================

-- ── Permission vocabulary (Spatie `permissions`) ─────────────────────────────
-- GLOBAL vocabulary (guard-scoped), not tenant-scoped: the capability strings
-- ('course.view', 'quiz.attempt', 'grade.*') are platform-defined.
CREATE TABLE permissions (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  name        TEXT NOT NULL,                       -- e.g. quiz.attempt ; grade.* (wildcard)
  guard_name  TEXT NOT NULL DEFAULT 'web',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (name, guard_name)
);

-- ── Roles (Spatie `roles`, team-scoped by tenant) ────────────────────────────
-- tenant_id NULL = a platform/system role template; non-null = tenant-owned role.
CREATE TABLE roles (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  tenant_id   UUID REFERENCES tenants(id) ON DELETE CASCADE,   -- Spatie team key
  name        TEXT NOT NULL,                       -- teacher|student|manager|...
  guard_name  TEXT NOT NULL DEFAULT 'web',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- role name unique within a tenant (and within the NULL/system scope)
  UNIQUE (tenant_id, name, guard_name)
);
-- Spatie treats NULL team as a distinct bucket; emulate "one system role per name"
CREATE UNIQUE INDEX uq_roles_system_name ON roles (name, guard_name)
  WHERE tenant_id IS NULL;

-- ── role ↔ permission (Spatie `role_has_permissions`) ────────────────────────
CREATE TABLE role_has_permissions (
  permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  role_id       UUID NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
  PRIMARY KEY (permission_id, role_id)
);

-- ── Direct model→role / model→permission (Spatie tenant-wide assignments) ────
-- Used for tenant-level grants (e.g. tenant admin). Course/category/module
-- scoping lives in context_role_assignments below.
CREATE TABLE model_has_roles (
  role_id     UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,  -- team key
  model_type  TEXT NOT NULL DEFAULT 'App\\Models\\User',
  model_id    UUID NOT NULL,                        -- users.id
  PRIMARY KEY (role_id, model_id, tenant_id)
);
CREATE INDEX idx_mhr_model ON model_has_roles (tenant_id, model_id);

CREATE TABLE model_has_permissions (
  permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  model_type    TEXT NOT NULL DEFAULT 'App\\Models\\User',
  model_id      UUID NOT NULL,
  PRIMARY KEY (permission_id, model_id, tenant_id)
);
CREATE INDEX idx_mhp_model ON model_has_permissions (tenant_id, model_id);

-- ── The context tree (custom; Spatie has no concept of this) ─────────────────
-- One row per node in: system → tenant → category → course → module → user.
-- path is the ltree materialized path; "all contexts under X" = path <@ X.path.
CREATE TABLE contexts (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  level       TEXT  NOT NULL,                       -- system|tenant|category|course|module|user
  instance_id UUID  NOT NULL,                       -- id of the wrapped thing
  parent_id   UUID  REFERENCES contexts(id) ON DELETE CASCADE,
  path        LTREE NOT NULL,                       -- e.g. t_<uuid>.cat_<uuid>.crs_<uuid>
  depth       INT   NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ctx_level_chk CHECK (level IN ('system','tenant','category','course','module','user')),
  CONSTRAINT ctx_instance_uq UNIQUE (tenant_id, level, instance_id)
);
-- Composite GiST so ancestor/descendant queries stay on one tenant's subtree.
-- (Requires btree_gist for the leading uuid equality column.)
CREATE INDEX idx_contexts_tenant_path ON contexts USING GIST (tenant_id, path);
CREATE INDEX idx_contexts_instance ON contexts (tenant_id, level, instance_id);

-- ── Context-scoped role assignment (custom; the heart of contextual RBAC) ────
-- Binds (user, role, context). "teacher in course A, student in course B".
CREATE TABLE context_role_assignments (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  role_id     UUID NOT NULL REFERENCES roles(id)   ON DELETE CASCADE,
  context_id  UUID NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, user_id, role_id, context_id)
);
CREATE INDEX idx_cra_user_ctx ON context_role_assignments (tenant_id, user_id, context_id);
CREATE INDEX idx_cra_context  ON context_role_assignments (tenant_id, context_id);

-- ── Optional explicit deny (only if a vertical needs Moodle-style PROHIBIT) ──
CREATE TABLE permission_overrides (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  context_id  UUID NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
  role_id     UUID REFERENCES roles(id) ON DELETE CASCADE,   -- override for a role...
  user_id     UUID REFERENCES users(id) ON DELETE CASCADE,   -- ...or a user
  permission  TEXT NOT NULL,
  effect      SMALLINT NOT NULL,                    -- -1 prevent, -1000 prohibit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT po_effect_chk CHECK (effect IN (-1, -1000)),
  -- exactly one of role_id / user_id must be set
  CONSTRAINT po_target_chk CHECK ((role_id IS NULL) <> (user_id IS NULL))
);
-- two partial unique indexes: NULLs in the key would otherwise defeat uniqueness
CREATE UNIQUE INDEX uq_po_role ON permission_overrides (tenant_id, context_id, role_id, permission)
  WHERE role_id IS NOT NULL;
CREATE UNIQUE INDEX uq_po_user ON permission_overrides (tenant_id, context_id, user_id, permission)
  WHERE user_id IS NOT NULL;
